# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.21.4
enabled_platforms=fabric

archives_base_name=ContingameIMESuper
mod_version=1.0.12
maven_group=dev.soldierrmb

# Plugins
architecturyPluginVersion=3.4.161
loomPluginVersion=1.9.428
unifiedPublishingVersion=0.1.13
kotlinJvmVersion=2.1.10

architectury_version=14.0.4
architectury_fabric_version=14.0.4

cloth_config_version=16.0.143
cloth_config_fabric_version=16.0.143
rei_fabric_version=17.0.794

# Common
yarn_mappings=1.21.4+build.8
loader_version=0.16.10
fabric_version=0.118.5+1.21.4
# https://github.com/FabricMC/fabric-language-kotlin
fabric_language_kotlin_version=1.13.1+kotlin.2.1.10
satin_version=2.0.0

kotlin_version=2.1.10